In [1]:
x = "Adam"
y = "Karton"

x.split("d")[0]

'A'

In [2]:
x.rstrip("am")

'Ad'

In [3]:
mylist = [1, 2, 3, 4, 5]
yourlist = [10, 11, 12, 13]
mylist.extend(yourlist)
mylist

[1, 2, 3, 4, 5, 10, 11, 12, 13]

In [4]:
mylist.pop(4)
mylist

[1, 2, 3, 4, 10, 11, 12, 13]

In [5]:
new_list = []

for i in range(1, 11):
    new_list.append(i)

new_list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [6]:
newer_list=[i for i in range(1,11)]
newer_list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [7]:
'''
Write a Python program to create a lambda function that adds 15 to a given number passed in as an argument, 
also create a lambda function that multiplies argument x with argument y and print the result. 
'''

x = lambda x: x+15
y = lambda x, y: x*y

print(x(10))
print(y(2, 5))

25
10


In [8]:
'''
Write a Python program to create a function that takes one argument, and that argument
will be multiplied with an unknown given number. Go to the editor
'''

def func(n):
    lambda x: x*n
    return x
func(2)

<function __main__.<lambda>(x)>

In [9]:
def func_compute(n):
    return lambda x : x * n
result = func_compute(2)
print("Double the number of 10 =", result(15))

Double the number of 10 = 30


In [10]:
import numpy as np
another_list = [[1,2,3], [4,5,6]]
b = np.array(another_list)
print(b)
b[1][1]

[[1 2 3]
 [4 5 6]]


5

In [11]:
np.sum(b, axis=0)

array([5, 7, 9])

In [12]:
q = np.array([1,2,3])
r = np.array([4,5,6])
t = np.add(r, q)
print(t)

[5 7 9]


In [13]:
list(map(lambda x: x**2 if x < 7 else x, t))

[25, 7, 9]

In [14]:
import pandas as pd
f = pd.Series(np.random.random(10))
print(f)
type(f)

0    0.627831
1    0.418209
2    0.379862
3    0.400538
4    0.139157
5    0.909034
6    0.173025
7    0.291783
8    0.379842
9    0.293494
dtype: float64


pandas.core.series.Series

In [15]:
df = pd.DataFrame(np.random.randint(0,100,size=(10, 4)), columns=list('ABCD'))
df.head(3)

A   B   C   D
0  62  82   2   5
1  58  92  12  84
2   5  89   0  64

In [16]:
colnames = ["Adam", "Gosia", "Kasia", "Marek"]
df2 = pd.DataFrame(np.random.random((10,4)), columns = colnames)
df2.head(2)

Adam    Gosia     Kasia     Marek
0  0.355209  0.35655  0.271046  0.494814
1  0.091698  0.48242  0.470274  0.641744

In [17]:
leest = [7, 8, "male", 1, 0, 12]
leest2 = [21, 21, "male", 4, 656, 5]
leest3 = [1, 2, 3, 4, "male", 6]
colnamen = ["Adam", "Jadzia", "Ben", "Bob", "Rob", "Dug"]
df3 = pd.DataFrame(data = [leest, leest2, leest3], columns = colnamen)
df3

Adam  Jadzia   Ben  Bob   Rob  Dug
0     7       8  male    1     0   12
1    21      21  male    4   656    5
2     1       2     3    4  male    6

In [18]:
list(df3.columns)

['Adam', 'Jadzia', 'Ben', 'Bob', 'Rob', 'Dug']

In [19]:
p = df3[["Adam"]]
print(p)
type(p)

   Adam
0     7
1    21
2     1


pandas.core.frame.DataFrame

In [20]:
ü = df3[["Adam", "Ben"]]
ü

Adam   Ben
0     7  male
1    21  male
2     1     3

In [21]:
df3.head(5)

Adam  Jadzia   Ben  Bob   Rob  Dug
0     7       8  male    1     0   12
1    21      21  male    4   656    5
2     1       2     3    4  male    6

In [22]:
ds = df3.loc[[1,2], :]
print(ds)
type(ds)

   Adam  Jadzia   Ben  Bob   Rob  Dug
1    21      21  male    4   656    5
2     1       2     3    4  male    6


pandas.core.frame.DataFrame

In [23]:
dsw = df3.loc[:, "Ben"]
print(dsw)

0    male
1    male
2       3
Name: Ben, dtype: object


In [24]:
gf = df3.loc[df3.Ben == "male", "Jadzia"]
gf

0     8
1    21
Name: Jadzia, dtype: int64

In [25]:
gz = df3.iloc[:, [0,1]]
gz

Adam  Jadzia
0     7       8
1    21      21
2     1       2

In [26]:
df3.rename({"Adam": "Dadam"}, axis = 1, inplace = True)


In [27]:
df3


Dadam  Jadzia   Ben  Bob   Rob  Dug
0      7       8  male    1     0   12
1     21      21  male    4   656    5
2      1       2     3    4  male    6

In [28]:
df3.Dadam.astype(str)
u = df3.Dadam
print(u)
type(u[0])

0     7
1    21
2     1
Name: Dadam, dtype: int64


numpy.int64

In [29]:
df3.describe()

Dadam     Jadzia       Bob        Dug
count   3.000000   3.000000  3.000000   3.000000
mean    9.666667  10.333333  3.000000   7.666667
std    10.263203   9.712535  1.732051   3.785939
min     1.000000   2.000000  1.000000   5.000000
25%     4.000000   5.000000  2.500000   5.500000
50%     7.000000   8.000000  4.000000   6.000000
75%    14.000000  14.500000  4.000000   9.000000
max    21.000000  21.000000  4.000000  12.000000

In [30]:
df3.loc[df3['Ben'] == 3]

Dadam  Jadzia Ben  Bob   Rob  Dug
2      1       2   3    4  male    6

In [31]:
data_url = 'http://bit.ly/2cLzoxH'
gapminder = pd.read_csv(data_url)
gapminder.head

<bound method NDFrame.head of           country  year         pop continent  lifeExp   gdpPercap
0     Afghanistan  1952   8425333.0      Asia   28.801  779.445314
1     Afghanistan  1957   9240934.0      Asia   30.332  820.853030
2     Afghanistan  1962  10267083.0      Asia   31.997  853.100710
3     Afghanistan  1967  11537966.0      Asia   34.020  836.197138
4     Afghanistan  1972  13079460.0      Asia   36.088  739.981106
...           ...   ...         ...       ...      ...         ...
1699     Zimbabwe  1987   9216418.0    Africa   62.351  706.157306
1700     Zimbabwe  1992  10704340.0    Africa   60.377  693.420786
1701     Zimbabwe  1997  11404948.0    Africa   46.809  792.449960
1702     Zimbabwe  2002  11926563.0    Africa   39.989  672.038623
1703     Zimbabwe  2007  12311143.0    Africa   43.487  469.709298

[1704 rows x 6 columns]>

In [32]:
is_2002 = gapminder["year"] == 2002
is_2002

0       False
1       False
2       False
3       False
4       False
        ...  
1699    False
1700    False
1701    False
1702     True
1703    False
Name: year, Length: 1704, dtype: bool

In [33]:
df_is_2002 = gapminder[is_2002]
df_is_2002

country  year         pop continent  lifeExp    gdpPercap
10           Afghanistan  2002  25268405.0      Asia   42.129   726.734055
22               Albania  2002   3508512.0    Europe   75.651  4604.211737
34               Algeria  2002  31287142.0    Africa   70.994  5288.040382
46                Angola  2002  10866106.0    Africa   41.003  2773.287312
58             Argentina  2002  38331121.0  Americas   74.340  8797.640716
...                  ...   ...         ...       ...      ...          ...
1654             Vietnam  2002  80908147.0      Asia   73.017  1764.456677
1666  West Bank and Gaza  2002   3389578.0      Asia   72.370  4515.487575
1678          Yemen Rep.  2002  18701257.0      Asia   60.308  2234.820827
1690              Zambia  2002  10595811.0    Africa   39.193  1071.613938
1702            Zimbabwe  2002  11926563.0    Africa   39.989   672.038623

[142 rows x 6 columns]

In [34]:
filtered_df3 = df3[(df3["Ben"] == "male") | (df3["Dadam"] == 21)]
filtered_df3

Dadam  Jadzia   Ben  Bob  Rob  Dug
0      7       8  male    1    0   12
1     21      21  male    4  656    5

In [35]:
df_is_2002.drop(labels = [58, 34], axis = 0, inplace = True)
df_is_2002

C:\Users\atycn\anaconda3\lib\site-packages\pandas\core\frame.py:4906: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(


country  year         pop continent  lifeExp     gdpPercap
10           Afghanistan  2002  25268405.0      Asia   42.129    726.734055
22               Albania  2002   3508512.0    Europe   75.651   4604.211737
46                Angola  2002  10866106.0    Africa   41.003   2773.287312
70             Australia  2002  19546792.0   Oceania   80.370  30687.754730
82               Austria  2002   8148312.0    Europe   78.980  32417.607690
...                  ...   ...         ...       ...      ...           ...
1654             Vietnam  2002  80908147.0      Asia   73.017   1764.456677
1666  West Bank and Gaza  2002   3389578.0      Asia   72.370   4515.487575
1678          Yemen Rep.  2002  18701257.0      Asia   60.308   2234.820827
1690              Zambia  2002  10595811.0    Africa   39.193   1071.613938
1702            Zimbabwe  2002  11926563.0    Africa   39.989    672.038623

[140 rows x 6 columns]

In [45]:
fds = df_is_2002.drop(df_is_2002.index[range(5)])
fds

country  year          pop continent  lifeExp     gdpPercap
94               Bahrain  2002     656397.0      Asia   74.795  23403.559270
106           Bangladesh  2002  135656790.0      Asia   62.013   1136.390430
118              Belgium  2002   10311970.0    Europe   78.320  30485.883750
130                Benin  2002    7026113.0    Africa   54.406   1372.877931
142              Bolivia  2002    8445134.0  Americas   63.883   3413.262690
...                  ...   ...          ...       ...      ...           ...
1654             Vietnam  2002   80908147.0      Asia   73.017   1764.456677
1666  West Bank and Gaza  2002    3389578.0      Asia   72.370   4515.487575
1678          Yemen Rep.  2002   18701257.0      Asia   60.308   2234.820827
1690              Zambia  2002   10595811.0    Africa   39.193   1071.613938
1702            Zimbabwe  2002   11926563.0    Africa   39.989    672.038623

[135 rows x 6 columns]

In [46]:
df_is_2002.drop(1702)

country  year         pop continent  lifeExp     gdpPercap
10           Afghanistan  2002  25268405.0      Asia   42.129    726.734055
22               Albania  2002   3508512.0    Europe   75.651   4604.211737
46                Angola  2002  10866106.0    Africa   41.003   2773.287312
70             Australia  2002  19546792.0   Oceania   80.370  30687.754730
82               Austria  2002   8148312.0    Europe   78.980  32417.607690
...                  ...   ...         ...       ...      ...           ...
1642           Venezuela  2002  24287670.0  Americas   72.766   8605.047831
1654             Vietnam  2002  80908147.0      Asia   73.017   1764.456677
1666  West Bank and Gaza  2002   3389578.0      Asia   72.370   4515.487575
1678          Yemen Rep.  2002  18701257.0      Asia   60.308   2234.820827
1690              Zambia  2002  10595811.0    Africa   39.193   1071.613938

[139 rows x 6 columns]

In [48]:
df_is_2002 = df_is_2002[df_is_2002["continent"] != "Asia"]

In [49]:
df_is_2002

country  year          pop continent  lifeExp     gdpPercap
22          Albania  2002    3508512.0    Europe   75.651   4604.211737
46           Angola  2002   10866106.0    Africa   41.003   2773.287312
70        Australia  2002   19546792.0   Oceania   80.370  30687.754730
82          Austria  2002    8148312.0    Europe   78.980  32417.607690
118         Belgium  2002   10311970.0    Europe   78.320  30485.883750
...             ...   ...          ...       ...      ...           ...
1618  United States  2002  287675526.0  Americas   77.310  39097.099550
1630        Uruguay  2002    3363085.0  Americas   75.307   7727.002004
1642      Venezuela  2002   24287670.0  Americas   72.766   8605.047831
1690         Zambia  2002   10595811.0    Africa   39.193   1071.613938
1702       Zimbabwe  2002   11926563.0    Africa   39.989    672.038623

[107 rows x 6 columns]

In [57]:
df_is_2002 = df_is_2002[(df_is_2002["continent"] != "Americas")]
df_is_2002

country  year         pop continent  lifeExp  \
22                   Albania  2002   3508512.0    Europe   75.651   
70                 Australia  2002  19546792.0   Oceania   80.370   
82                   Austria  2002   8148312.0    Europe   78.980   
118                  Belgium  2002  10311970.0    Europe   78.320   
154   Bosnia and Herzegovina  2002   4165416.0    Europe   74.090   
190                 Bulgaria  2002   7661799.0    Europe   72.140   
382                  Croatia  2002   4481020.0    Europe   74.876   
406           Czech Republic  2002  10256295.0    Europe   75.510   
418                  Denmark  2002   5374693.0    Europe   77.180   
526                  Finland  2002   5193039.0    Europe   78.370   
538                   France  2002  59925035.0    Europe   79.590   
574                  Germany  2002  82350671.0    Europe   78.670   
598                   Greece  2002  10603863.0    Europe   78.256   
682                  Hungary  2002  10083313.0    Europe   72.590   
694                  Iceland  2002    288030.0    Europe   80.500   
754                  Ireland  2002   3879155.0    Europe   77.783   
778                    Italy  2002  57926999.0    Europe   80.240   
1018              Montenegro  2002    720230.0    Europe   73.981   
1090             Netherlands  2002  16122830.0    Europe   78.530   
1102             New Zealand  2002   3908037.0   Oceania   79.110   
1150                  Norway  2002   4535591.0    Europe   79.050   
1234                  Poland  2002  38625976.0    Europe   74.670   
1246                Portugal  2002  10433867.0    Europe   77.290   
1282                 Romania  2002  22404337.0    Europe   71.322   
1342                  Serbia  2002  10111559.0    Europe   73.213   
1378         Slovak Republic  2002   5410052.0    Europe   73.800   
1390                Slovenia  2002   2011497.0    Europe   76.660   
1426                   Spain  2002  40152517.0    Europe   79.780   
1474                  Sweden  2002   8954175.0    Europe   80.040   
1486             Switzerland  2002   7361757.0    Europe   80.620   
1582                  Turkey  2002  67308928.0    Europe   70.845   
1606          United Kingdom  2002  59912431.0    Europe   78.471   

         gdpPercap  
22     4604.211737  
70    30687.754730  
82    32417.607690  
118   30485.883750  
154    6018.975239  
190    7696.777725  
382   11628.388950  
406   17596.210220  
418   32166.500060  
526   28204.590570  
538   28926.032340  
574   30035.801980  
598   22514.254800  
682   14843.935560  
694   31163.201960  
754   34077.049390  
778   27968.098170  
1018   6557.194282  
1090  33724.757780  
1102  23189.801350  
1150  44683.975250  
1234  12002.239080  
1246  19970.907870  
1282   7885.360081  
1342   7236.075251  
1378  13638.778370  
1390  20660.019360  
1426  24835.471660  
1474  29341.630930  
1486  34480.957710  
1582   6508.085718  
1606  29478.999190

In [65]:
df4 = pd.read_csv("https://bit.ly/3kGDuKx")
df4.head(7)

pclass  survived                                             name     sex  \
0       1         1                    Allen, Miss. Elisabeth Walton  female   
1       1         1                   Allison, Master. Hudson Trevor    male   
2       1         0                     Allison, Miss. Helen Loraine  female   
3       1         0             Allison, Mr. Hudson Joshua Creighton    male   
4       1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female   
5       1         1                              Anderson, Mr. Harry    male   
6       1         1                Andrews, Miss. Kornelia Theodosia  female   

      age  sibsp  parch  ticket      fare    cabin embarked boat body  \
0      29      0      0   24160  211.3375       B5        S    2    ?   
1  0.9167      1      2  113781    151.55  C22 C26        S   11    ?   
2       2      1      2  113781    151.55  C22 C26        S    ?    ?   
3      30      1      2  113781    151.55  C22 C26        S    ?  135   
4      25      1      2  113781    151.55  C22 C26        S    ?    ?   
5      48      0      0   19952     26.55      E12        S    3    ?   
6      63      1      0   13502   77.9583       D7        S   10    ?   

                         home.dest  
0                     St Louis, MO  
1  Montreal, PQ / Chesterville, ON  
2  Montreal, PQ / Chesterville, ON  
3  Montreal, PQ / Chesterville, ON  
4  Montreal, PQ / Chesterville, ON  
5                     New York, NY  
6                       Hudson, NY

In [80]:
df4.groupby(["sex"])["survived"].count()

sex
female    466
male      843
Name: survived, dtype: int64